/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : LED_VERD.h
**     Project     : teste11_K64F_PE_sem_KSDK
**     Processor   : MK64FN1M0VLL12
**     Component   : LED
**     Version     : Component 01.062, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2014-09-26, 19:45, # CodeGen: 2
**     Abstract    :
**          This component implements a universal driver for a single LED.
**     Settings    :
**          Component name                                 : LED_VERD
**          Turned On with initialization                  : no
**          HW Interface                                   : 
**            On/Off                                       : Enabled
**              Pin                                        : LEDpin
**            PWM                                          : Disabled
**            High Value means ON                          : no
**          Shell                                          : Disabled
**     Contents    :
**         Init       - void LED_VERD_Init(void);
**         Deinit     - void LED_VERD_Deinit(void);
**         On         - void LED_VERD_On(void);
**         Off        - void LED_VERD_Off(void);
**         Neg        - void LED_VERD_Neg(void);
**         Get        - byte LED_VERD_Get(void);
**         Put        - void LED_VERD_Put(byte val);
**         SetRatio16 - void LED_VERD_SetRatio16(word ratio);
**
**     License   : Open Source (LGPL)
**     Copyright : Erich Styger, 2013, all rights reserved.
**     Web       : www.mcuoneclipse.com
**     This an open source software implementing a driver using Processor Expert.
**     This is a free software and is opened for education, research and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file LED_VERD.h
** @version 01.00
** @brief
**          This component implements a universal driver for a single LED.
*/         
/*!
**  @addtogroup LED_VERD_module LED_VERD module documentation
**  @{
*/         

#ifndef __LED_VERD_H
#define __LED_VERD_H

/* MODULE LED_VERD. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "LEDpin1.h"

#include "Cpu.h"

#define LED_VERD_ClrVal()    LEDpin1_ClrVal() /* put the pin on low level */
#define LED_VERD_SetVal()    LEDpin1_SetVal() /* put the pin on high level */
#define LED_VERD_SetInput()  LEDpin1_SetInput() /* use the pin as input pin */
#define LED_VERD_SetOutput() LEDpin1_SetOutput() /* use the pin as output pin */

#define LED_VERD_PARSE_COMMAND_ENABLED  0 /* set to 1 if method ParseCommand() is present, 0 otherwise */


#define LED_VERD_On() LEDpin1_ClrVal()
/*
** ===================================================================
**     Method      :  LED_VERD_On (component LED)
**     Description :
**         This turns the LED on.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LED_VERD_Off() LEDpin1_SetVal()
/*
** ===================================================================
**     Method      :  LED_VERD_Off (component LED)
**     Description :
**         This turns the LED off.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LED_VERD_Neg() LEDpin1_NegVal()
/*
** ===================================================================
**     Method      :  LED_VERD_Neg (component LED)
**     Description :
**         This negates/toggles the LED
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LED_VERD_Get() (!(LEDpin1_GetVal()))
/*
** ===================================================================
**     Method      :  LED_VERD_Get (component LED)
**     Description :
**         This returns logical 1 in case the LED is on, 0 otherwise.
**     Parameters  : None
**     Returns     :
**         ---             - Status of the LED (on or off)
** ===================================================================
*/

#define LED_VERD_Init() LED_VERD_Off()
/*
** ===================================================================
**     Method      :  LED_VERD_Init (component LED)
**     Description :
**         Performs the LED driver initialization.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LED_VERD_Put(val)  ((val) ? LED_VERD_On() : LED_VERD_Off())
/*
** ===================================================================
**     Method      :  LED_VERD_Put (component LED)
**     Description :
**         Turns the LED on or off.
**     Parameters  :
**         NAME            - DESCRIPTION
**         val             - value to define if the LED has to be on or
**                           off.
**     Returns     : Nothing
** ===================================================================
*/

void LED_VERD_Deinit(void);
/*
** ===================================================================
**     Method      :  LED_VERD_Deinit (component LED)
**     Description :
**         Deinitializes the driver
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void LED_VERD_SetRatio16(word ratio);
/*
** ===================================================================
**     Method      :  LED_VERD_SetRatio16 (component LED)
**     Description :
**         Method to specify the duty cycle. If using a PWM pin, this
**         means the duty cycle is set. For On/off pins, values smaller
**         0x7FFF means off, while values greater means on.
**     Parameters  :
**         NAME            - DESCRIPTION
**         ratio           - Ratio value, where 0 means 'off' and
**                           0xffff means 'on'
**     Returns     : Nothing
** ===================================================================
*/

/* END LED_VERD. */

#endif
/* ifndef __LED_VERD_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.4 [05.10]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
