/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : LED_AZUL.h
**     Project     : HelloWorld_K64F_teste11_PE
**     Processor   : MK64FN1M0VLL12
**     Component   : LED
**     Version     : Component 01.062, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2014-09-27, 18:35, # CodeGen: 1
**     Abstract    :
**          This component implements a universal driver for a single LED.
**     Settings    :
**          Component name                                 : LED_AZUL
**          Turned On with initialization                  : yes
**          HW Interface                                   : 
**            On/Off                                       : Enabled
**              Pin                                        : LEDpin
**            PWM                                          : Disabled
**            High Value means ON                          : no
**          Shell                                          : Disabled
**     Contents    :
**         Init       - void LED_AZUL_Init(void);
**         Deinit     - void LED_AZUL_Deinit(void);
**         On         - void LED_AZUL_On(void);
**         Off        - void LED_AZUL_Off(void);
**         Neg        - void LED_AZUL_Neg(void);
**         Get        - byte LED_AZUL_Get(void);
**         Put        - void LED_AZUL_Put(byte val);
**         SetRatio16 - void LED_AZUL_SetRatio16(word ratio);
**
**     License   : Open Source (LGPL)
**     Copyright : Erich Styger, 2013, all rights reserved.
**     Web       : www.mcuoneclipse.com
**     This an open source software implementing a driver using Processor Expert.
**     This is a free software and is opened for education, research and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file LED_AZUL.h
** @version 01.00
** @brief
**          This component implements a universal driver for a single LED.
*/         
/*!
**  @addtogroup LED_AZUL_module LED_AZUL module documentation
**  @{
*/         

#ifndef __LED_AZUL_H
#define __LED_AZUL_H

/* MODULE LED_AZUL. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "LEDpin2.h"

#include "Cpu.h"

#define LED_AZUL_ClrVal()    LEDpin2_ClrVal() /* put the pin on low level */
#define LED_AZUL_SetVal()    LEDpin2_SetVal() /* put the pin on high level */
#define LED_AZUL_SetInput()  LEDpin2_SetInput() /* use the pin as input pin */
#define LED_AZUL_SetOutput() LEDpin2_SetOutput() /* use the pin as output pin */

#define LED_AZUL_PARSE_COMMAND_ENABLED  0 /* set to 1 if method ParseCommand() is present, 0 otherwise */


#define LED_AZUL_On() LEDpin2_ClrVal()
/*
** ===================================================================
**     Method      :  LED_AZUL_On (component LED)
**     Description :
**         This turns the LED on.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LED_AZUL_Off() LEDpin2_SetVal()
/*
** ===================================================================
**     Method      :  LED_AZUL_Off (component LED)
**     Description :
**         This turns the LED off.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LED_AZUL_Neg() LEDpin2_NegVal()
/*
** ===================================================================
**     Method      :  LED_AZUL_Neg (component LED)
**     Description :
**         This negates/toggles the LED
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LED_AZUL_Get() (!(LEDpin2_GetVal()))
/*
** ===================================================================
**     Method      :  LED_AZUL_Get (component LED)
**     Description :
**         This returns logical 1 in case the LED is on, 0 otherwise.
**     Parameters  : None
**     Returns     :
**         ---             - Status of the LED (on or off)
** ===================================================================
*/

#define LED_AZUL_Init() LED_AZUL_On()
/*
** ===================================================================
**     Method      :  LED_AZUL_Init (component LED)
**     Description :
**         Performs the LED driver initialization.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LED_AZUL_Put(val)  ((val) ? LED_AZUL_On() : LED_AZUL_Off())
/*
** ===================================================================
**     Method      :  LED_AZUL_Put (component LED)
**     Description :
**         Turns the LED on or off.
**     Parameters  :
**         NAME            - DESCRIPTION
**         val             - value to define if the LED has to be on or
**                           off.
**     Returns     : Nothing
** ===================================================================
*/

void LED_AZUL_Deinit(void);
/*
** ===================================================================
**     Method      :  LED_AZUL_Deinit (component LED)
**     Description :
**         Deinitializes the driver
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void LED_AZUL_SetRatio16(word ratio);
/*
** ===================================================================
**     Method      :  LED_AZUL_SetRatio16 (component LED)
**     Description :
**         Method to specify the duty cycle. If using a PWM pin, this
**         means the duty cycle is set. For On/off pins, values smaller
**         0x7FFF means off, while values greater means on.
**     Parameters  :
**         NAME            - DESCRIPTION
**         ratio           - Ratio value, where 0 means 'off' and
**                           0xffff means 'on'
**     Returns     : Nothing
** ===================================================================
*/

/* END LED_AZUL. */

#endif
/* ifndef __LED_AZUL_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.4 [05.10]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
