/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : pin_mux.c
**     Project     : teste11_K64F_PE_sem_KSDK
**     Processor   : MK64FN1M0VLL12
**     Component   : PinSettings
**     Version     : Component 01.002, Driver 1.1, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2014-09-26, 19:37, # CodeGen: 0
**     Abstract    :
**
**     Settings    :
**
**     Contents    :
**         hardware_init       - void hardware_init(void);
**         configure_can_pins  - void configure_can_pins(uint32_t instance);
**         configure_cmp_pins  - void configure_cmp_pins(uint32_t instance);
**         configure_enet_pins - void configure_enet_pins(uint32_t instance);
**         configure_gpio_pins - void configure_gpio_pins(uint32_t instance);
**         configure_i2c_pins  - void configure_i2c_pins(uint32_t instance);
**         configure_i2s_pins  - void configure_i2s_pins(uint32_t instance);
**         configure_jtag_pins - void configure_jtag_pins(uint32_t instance);
**         configure_llwu_pins - void configure_llwu_pins(uint32_t instance);
**         configure_rtc_pins  - void configure_rtc_pins(uint32_t instance);
**         configure_sdhc_pins - void configure_sdhc_pins(uint32_t instance);
**         configure_spi_pins  - void configure_spi_pins(uint32_t instance);
**         configure_uart_pins - void configure_uart_pins(uint32_t instance);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file pin_mux.c
** @version 1.1
** @brief
**
*/         
/*!
**  @addtogroup pin_mux_module pin_mux module documentation
**  @{
*/         

/* MODULE pin_mux. */

#include "pin_mux.h"
#include "PE_Types.h"
#include "IO_Map.h"

/*
** ===================================================================
**     Method      :  pin_mux_hardware_init (component PinSettings)
*/
/*!
**     @brief
**         This method sets registers according routing settings. Call
**         this method in user code to route desired pins into
**         peripherals. The method is useful for reinitialization HW
**         after some routing changes.
*/
/* ===================================================================*/
void pin_mux_hardware_init(void)
{
  /* PORTB_PCR19: ISF=0,MUX=2,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTB_PCR19 = (uint32_t)((PORTB_PCR19 & (uint32_t)~(uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_MUX(0x05) |
                 PORT_PCR_DSE_MASK |
                 PORT_PCR_ODE_MASK |
                 PORT_PCR_PFE_MASK |
                 PORT_PCR_SRE_MASK |
                 PORT_PCR_PE_MASK |
                 PORT_PCR_PS_MASK
                )) | (uint32_t)(
                 PORT_PCR_MUX(0x02)
                ));
  /* PORTB_PCR18: ISF=0,MUX=2,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTB_PCR18 = (uint32_t)((PORTB_PCR18 & (uint32_t)~(uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_MUX(0x05) |
                 PORT_PCR_DSE_MASK |
                 PORT_PCR_ODE_MASK |
                 PORT_PCR_PFE_MASK |
                 PORT_PCR_SRE_MASK |
                 PORT_PCR_PE_MASK |
                 PORT_PCR_PS_MASK
                )) | (uint32_t)(
                 PORT_PCR_MUX(0x02)
                ));
  /* PORTB_PCR20: ISF=0,MUX=6,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTB_PCR20 = (uint32_t)((PORTB_PCR20 & (uint32_t)~(uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_MUX(0x01) |
                 PORT_PCR_DSE_MASK |
                 PORT_PCR_ODE_MASK |
                 PORT_PCR_PFE_MASK |
                 PORT_PCR_SRE_MASK |
                 PORT_PCR_PE_MASK |
                 PORT_PCR_PS_MASK
                )) | (uint32_t)(
                 PORT_PCR_MUX(0x06)
                ));
  /* PORTC_PCR16: ISF=0,MUX=4,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTC_PCR16 = (uint32_t)((PORTC_PCR16 & (uint32_t)~(uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_MUX(0x03) |
                 PORT_PCR_DSE_MASK |
                 PORT_PCR_ODE_MASK |
                 PORT_PCR_PFE_MASK |
                 PORT_PCR_SRE_MASK |
                 PORT_PCR_PE_MASK |
                 PORT_PCR_PS_MASK
                )) | (uint32_t)(
                 PORT_PCR_MUX(0x04)
                ));
  /* PORTC_PCR17: ISF=0,MUX=4,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTC_PCR17 = (uint32_t)((PORTC_PCR17 & (uint32_t)~(uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_MUX(0x03) |
                 PORT_PCR_DSE_MASK |
                 PORT_PCR_ODE_MASK |
                 PORT_PCR_PFE_MASK |
                 PORT_PCR_SRE_MASK |
                 PORT_PCR_PE_MASK |
                 PORT_PCR_PS_MASK
                )) | (uint32_t)(
                 PORT_PCR_MUX(0x04)
                ));
  /* PORTC_PCR18: ISF=0,MUX=4,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTC_PCR18 = (uint32_t)((PORTC_PCR18 & (uint32_t)~(uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_MUX(0x03) |
                 PORT_PCR_DSE_MASK |
                 PORT_PCR_ODE_MASK |
                 PORT_PCR_PFE_MASK |
                 PORT_PCR_SRE_MASK |
                 PORT_PCR_PE_MASK |
                 PORT_PCR_PS_MASK
                )) | (uint32_t)(
                 PORT_PCR_MUX(0x04)
                ));
  /* PORTB_PCR1: ISF=0,MUX=4,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTB_PCR1 = (uint32_t)((PORTB_PCR1 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_MUX(0x03) |
                PORT_PCR_DSE_MASK |
                PORT_PCR_ODE_MASK |
                PORT_PCR_PFE_MASK |
                PORT_PCR_SRE_MASK |
                PORT_PCR_PE_MASK |
                PORT_PCR_PS_MASK
               )) | (uint32_t)(
                PORT_PCR_MUX(0x04)
               ));
  /* PORTB_PCR0: ISF=0,MUX=4,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTB_PCR0 = (uint32_t)((PORTB_PCR0 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_MUX(0x03) |
                PORT_PCR_DSE_MASK |
                PORT_PCR_ODE_MASK |
                PORT_PCR_PFE_MASK |
                PORT_PCR_SRE_MASK |
                PORT_PCR_PE_MASK |
                PORT_PCR_PS_MASK
               )) | (uint32_t)(
                PORT_PCR_MUX(0x04)
               ));
  /* PORTA_PCR13: ISF=0,MUX=4,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTA_PCR13 = (uint32_t)((PORTA_PCR13 & (uint32_t)~(uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_MUX(0x03) |
                 PORT_PCR_DSE_MASK |
                 PORT_PCR_ODE_MASK |
                 PORT_PCR_PFE_MASK |
                 PORT_PCR_SRE_MASK |
                 PORT_PCR_PE_MASK |
                 PORT_PCR_PS_MASK
                )) | (uint32_t)(
                 PORT_PCR_MUX(0x04)
                ));
  /* PORTA_PCR12: ISF=0,MUX=4,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTA_PCR12 = (uint32_t)((PORTA_PCR12 & (uint32_t)~(uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_MUX(0x03) |
                 PORT_PCR_DSE_MASK |
                 PORT_PCR_ODE_MASK |
                 PORT_PCR_PFE_MASK |
                 PORT_PCR_SRE_MASK |
                 PORT_PCR_PE_MASK |
                 PORT_PCR_PS_MASK
                )) | (uint32_t)(
                 PORT_PCR_MUX(0x04)
                ));
  /* PORTA_PCR14: ISF=0,MUX=4,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTA_PCR14 = (uint32_t)((PORTA_PCR14 & (uint32_t)~(uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_MUX(0x03) |
                 PORT_PCR_DSE_MASK |
                 PORT_PCR_ODE_MASK |
                 PORT_PCR_PFE_MASK |
                 PORT_PCR_SRE_MASK |
                 PORT_PCR_PE_MASK |
                 PORT_PCR_PS_MASK
                )) | (uint32_t)(
                 PORT_PCR_MUX(0x04)
                ));
  /* PORTA_PCR5: ISF=0,MUX=4,DSE=1,ODE=0,PFE=0,SRE=0,PE=0,PS=1 */
  PORTA_PCR5 = (uint32_t)((PORTA_PCR5 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_MUX(0x03) |
                PORT_PCR_ODE_MASK |
                PORT_PCR_PFE_MASK |
                PORT_PCR_SRE_MASK |
                PORT_PCR_PE_MASK
               )) | (uint32_t)(
                PORT_PCR_MUX(0x04) |
                PORT_PCR_DSE_MASK |
                PORT_PCR_PS_MASK
               ));
  /* PORTA_PCR16: ISF=0,MUX=4,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTA_PCR16 = (uint32_t)((PORTA_PCR16 & (uint32_t)~(uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_MUX(0x03) |
                 PORT_PCR_DSE_MASK |
                 PORT_PCR_ODE_MASK |
                 PORT_PCR_PFE_MASK |
                 PORT_PCR_SRE_MASK |
                 PORT_PCR_PE_MASK |
                 PORT_PCR_PS_MASK
                )) | (uint32_t)(
                 PORT_PCR_MUX(0x04)
                ));
  /* PORTA_PCR17: ISF=0,MUX=4,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTA_PCR17 = (uint32_t)((PORTA_PCR17 & (uint32_t)~(uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_MUX(0x03) |
                 PORT_PCR_DSE_MASK |
                 PORT_PCR_ODE_MASK |
                 PORT_PCR_PFE_MASK |
                 PORT_PCR_SRE_MASK |
                 PORT_PCR_PE_MASK |
                 PORT_PCR_PS_MASK
                )) | (uint32_t)(
                 PORT_PCR_MUX(0x04)
                ));
  /* PORTA_PCR15: ISF=0,MUX=4,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTA_PCR15 = (uint32_t)((PORTA_PCR15 & (uint32_t)~(uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_MUX(0x03) |
                 PORT_PCR_DSE_MASK |
                 PORT_PCR_ODE_MASK |
                 PORT_PCR_PFE_MASK |
                 PORT_PCR_SRE_MASK |
                 PORT_PCR_PE_MASK |
                 PORT_PCR_PS_MASK
                )) | (uint32_t)(
                 PORT_PCR_MUX(0x04)
                ));
  /* PORTA_PCR18: ISF=0,MUX=0,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTA_PCR18 &= (uint32_t)~(uint32_t)(
                  PORT_PCR_ISF_MASK |
                  PORT_PCR_MUX(0x07) |
                  PORT_PCR_DSE_MASK |
                  PORT_PCR_ODE_MASK |
                  PORT_PCR_PFE_MASK |
                  PORT_PCR_SRE_MASK |
                  PORT_PCR_PE_MASK |
                  PORT_PCR_PS_MASK
                 );
  /* PORTE_PCR24: ISF=0,MUX=5,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTE_PCR24 = (uint32_t)((PORTE_PCR24 & (uint32_t)~(uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_MUX(0x02) |
                 PORT_PCR_DSE_MASK |
                 PORT_PCR_ODE_MASK |
                 PORT_PCR_PFE_MASK |
                 PORT_PCR_SRE_MASK |
                 PORT_PCR_PE_MASK |
                 PORT_PCR_PS_MASK
                )) | (uint32_t)(
                 PORT_PCR_MUX(0x05)
                ));
  /* PORTE_PCR25: ISF=0,MUX=5,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTE_PCR25 = (uint32_t)((PORTE_PCR25 & (uint32_t)~(uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_MUX(0x02) |
                 PORT_PCR_DSE_MASK |
                 PORT_PCR_ODE_MASK |
                 PORT_PCR_PFE_MASK |
                 PORT_PCR_SRE_MASK |
                 PORT_PCR_PE_MASK |
                 PORT_PCR_PS_MASK
                )) | (uint32_t)(
                 PORT_PCR_MUX(0x05)
                ));
  /* PORTC_PCR10: ISF=0,MUX=2,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTC_PCR10 = (uint32_t)((PORTC_PCR10 & (uint32_t)~(uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_MUX(0x05) |
                 PORT_PCR_DSE_MASK |
                 PORT_PCR_ODE_MASK |
                 PORT_PCR_PFE_MASK |
                 PORT_PCR_SRE_MASK |
                 PORT_PCR_PE_MASK |
                 PORT_PCR_PS_MASK
                )) | (uint32_t)(
                 PORT_PCR_MUX(0x02)
                ));
  /* PORTC_PCR11: ISF=0,MUX=2,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTC_PCR11 = (uint32_t)((PORTC_PCR11 & (uint32_t)~(uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_MUX(0x05) |
                 PORT_PCR_DSE_MASK |
                 PORT_PCR_ODE_MASK |
                 PORT_PCR_PFE_MASK |
                 PORT_PCR_SRE_MASK |
                 PORT_PCR_PE_MASK |
                 PORT_PCR_PS_MASK
                )) | (uint32_t)(
                 PORT_PCR_MUX(0x02)
                ));
  /* PORTC_PCR8: ISF=0,MUX=4,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTC_PCR8 = (uint32_t)((PORTC_PCR8 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_MUX(0x03) |
                PORT_PCR_DSE_MASK |
                PORT_PCR_ODE_MASK |
                PORT_PCR_PFE_MASK |
                PORT_PCR_SRE_MASK |
                PORT_PCR_PE_MASK |
                PORT_PCR_PS_MASK
               )) | (uint32_t)(
                PORT_PCR_MUX(0x04)
               ));
  /* PORTC_PCR9: ISF=0,MUX=4,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTC_PCR9 = (uint32_t)((PORTC_PCR9 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_MUX(0x03) |
                PORT_PCR_DSE_MASK |
                PORT_PCR_ODE_MASK |
                PORT_PCR_PFE_MASK |
                PORT_PCR_SRE_MASK |
                PORT_PCR_PE_MASK |
                PORT_PCR_PS_MASK
               )) | (uint32_t)(
                PORT_PCR_MUX(0x04)
               ));
  /* PORTC_PCR7: ISF=0,MUX=4,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTC_PCR7 = (uint32_t)((PORTC_PCR7 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_MUX(0x03) |
                PORT_PCR_DSE_MASK |
                PORT_PCR_ODE_MASK |
                PORT_PCR_PFE_MASK |
                PORT_PCR_SRE_MASK |
                PORT_PCR_PE_MASK |
                PORT_PCR_PS_MASK
               )) | (uint32_t)(
                PORT_PCR_MUX(0x04)
               ));
  /* PORTC_PCR5: ISF=0,MUX=4,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTC_PCR5 = (uint32_t)((PORTC_PCR5 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_MUX(0x03) |
                PORT_PCR_DSE_MASK |
                PORT_PCR_ODE_MASK |
                PORT_PCR_PFE_MASK |
                PORT_PCR_SRE_MASK |
                PORT_PCR_PE_MASK |
                PORT_PCR_PS_MASK
               )) | (uint32_t)(
                PORT_PCR_MUX(0x04)
               ));
  /* PORTC_PCR1: ISF=0,MUX=6,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTC_PCR1 = (uint32_t)((PORTC_PCR1 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_MUX(0x01) |
                PORT_PCR_DSE_MASK |
                PORT_PCR_ODE_MASK |
                PORT_PCR_PFE_MASK |
                PORT_PCR_SRE_MASK |
                PORT_PCR_PE_MASK |
                PORT_PCR_PS_MASK
               )) | (uint32_t)(
                PORT_PCR_MUX(0x06)
               ));
  /* PORTA_PCR0: ISF=0,MUX=7,DSE=1,ODE=0,PFE=0,SRE=0,PE=1,PS=0 */
  PORTA_PCR0 = (uint32_t)((PORTA_PCR0 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_ODE_MASK |
                PORT_PCR_PFE_MASK |
                PORT_PCR_SRE_MASK |
                PORT_PCR_PS_MASK
               )) | (uint32_t)(
                PORT_PCR_MUX(0x07) |
                PORT_PCR_DSE_MASK |
                PORT_PCR_PE_MASK
               ));
  /* PORTA_PCR1: ISF=0,MUX=7,DSE=1,ODE=0,PFE=0,SRE=0,PE=1,PS=1 */
  PORTA_PCR1 = (uint32_t)((PORTA_PCR1 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_ODE_MASK |
                PORT_PCR_PFE_MASK |
                PORT_PCR_SRE_MASK
               )) | (uint32_t)(
                PORT_PCR_MUX(0x07) |
                PORT_PCR_DSE_MASK |
                PORT_PCR_PE_MASK |
                PORT_PCR_PS_MASK
               ));
  /* PORTA_PCR2: ISF=0,MUX=7,DSE=1,ODE=0,PFE=0,SRE=0,PE=1,PS=1 */
  PORTA_PCR2 = (uint32_t)((PORTA_PCR2 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_ODE_MASK |
                PORT_PCR_PFE_MASK |
                PORT_PCR_SRE_MASK
               )) | (uint32_t)(
                PORT_PCR_MUX(0x07) |
                PORT_PCR_DSE_MASK |
                PORT_PCR_PE_MASK |
                PORT_PCR_PS_MASK
               ));
  /* PORTA_PCR3: ISF=0,MUX=7,DSE=1,ODE=0,PFE=0,SRE=0,PE=1,PS=1 */
  PORTA_PCR3 = (uint32_t)((PORTA_PCR3 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_ODE_MASK |
                PORT_PCR_PFE_MASK |
                PORT_PCR_SRE_MASK
               )) | (uint32_t)(
                PORT_PCR_MUX(0x07) |
                PORT_PCR_DSE_MASK |
                PORT_PCR_PE_MASK |
                PORT_PCR_PS_MASK
               ));
  /* PORTA_PCR4: ISF=0,MUX=1,DSE=1,ODE=0,PFE=0,SRE=0,PE=1,PS=1 */
  PORTA_PCR4 = (uint32_t)((PORTA_PCR4 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_MUX(0x06) |
                PORT_PCR_ODE_MASK |
                PORT_PCR_PFE_MASK |
                PORT_PCR_SRE_MASK
               )) | (uint32_t)(
                PORT_PCR_MUX(0x01) |
                PORT_PCR_DSE_MASK |
                PORT_PCR_PE_MASK |
                PORT_PCR_PS_MASK
               ));
  /* PORTC_PCR6: ISF=0,MUX=1,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTC_PCR6 = (uint32_t)((PORTC_PCR6 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_MUX(0x06) |
                PORT_PCR_DSE_MASK |
                PORT_PCR_ODE_MASK |
                PORT_PCR_PFE_MASK |
                PORT_PCR_SRE_MASK |
                PORT_PCR_PE_MASK |
                PORT_PCR_PS_MASK
               )) | (uint32_t)(
                PORT_PCR_MUX(0x01)
               ));
  /* PORTA_PCR19: ISF=0,MUX=0,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTA_PCR19 &= (uint32_t)~(uint32_t)(
                  PORT_PCR_ISF_MASK |
                  PORT_PCR_MUX(0x07) |
                  PORT_PCR_DSE_MASK |
                  PORT_PCR_ODE_MASK |
                  PORT_PCR_PFE_MASK |
                  PORT_PCR_SRE_MASK |
                  PORT_PCR_PE_MASK |
                  PORT_PCR_PS_MASK
                 );
  /* PORTB_PCR21: ISF=0,MUX=1,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTB_PCR21 = (uint32_t)((PORTB_PCR21 & (uint32_t)~(uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_MUX(0x06) |
                 PORT_PCR_DSE_MASK |
                 PORT_PCR_ODE_MASK |
                 PORT_PCR_PFE_MASK |
                 PORT_PCR_SRE_MASK |
                 PORT_PCR_PE_MASK |
                 PORT_PCR_PS_MASK
                )) | (uint32_t)(
                 PORT_PCR_MUX(0x01)
                ));
  /* PORTB_PCR22: ISF=0,MUX=1,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTB_PCR22 = (uint32_t)((PORTB_PCR22 & (uint32_t)~(uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_MUX(0x06) |
                 PORT_PCR_DSE_MASK |
                 PORT_PCR_ODE_MASK |
                 PORT_PCR_PFE_MASK |
                 PORT_PCR_SRE_MASK |
                 PORT_PCR_PE_MASK |
                 PORT_PCR_PS_MASK
                )) | (uint32_t)(
                 PORT_PCR_MUX(0x01)
                ));
  /* PORTC_PCR0: ISF=0,MUX=1,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTC_PCR0 = (uint32_t)((PORTC_PCR0 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_MUX(0x06) |
                PORT_PCR_DSE_MASK |
                PORT_PCR_ODE_MASK |
                PORT_PCR_PFE_MASK |
                PORT_PCR_SRE_MASK |
                PORT_PCR_PE_MASK |
                PORT_PCR_PS_MASK
               )) | (uint32_t)(
                PORT_PCR_MUX(0x01)
               ));
  /* PORTC_PCR12: ISF=0,MUX=1,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTC_PCR12 = (uint32_t)((PORTC_PCR12 & (uint32_t)~(uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_MUX(0x06) |
                 PORT_PCR_DSE_MASK |
                 PORT_PCR_ODE_MASK |
                 PORT_PCR_PFE_MASK |
                 PORT_PCR_SRE_MASK |
                 PORT_PCR_PE_MASK |
                 PORT_PCR_PS_MASK
                )) | (uint32_t)(
                 PORT_PCR_MUX(0x01)
                ));
  /* PORTC_PCR13: ISF=0,MUX=1,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTC_PCR13 = (uint32_t)((PORTC_PCR13 & (uint32_t)~(uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_MUX(0x06) |
                 PORT_PCR_DSE_MASK |
                 PORT_PCR_ODE_MASK |
                 PORT_PCR_PFE_MASK |
                 PORT_PCR_SRE_MASK |
                 PORT_PCR_PE_MASK |
                 PORT_PCR_PS_MASK
                )) | (uint32_t)(
                 PORT_PCR_MUX(0x01)
                ));
  /* PORTE_PCR6: ISF=0,MUX=1,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTE_PCR6 = (uint32_t)((PORTE_PCR6 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_MUX(0x06) |
                PORT_PCR_DSE_MASK |
                PORT_PCR_ODE_MASK |
                PORT_PCR_PFE_MASK |
                PORT_PCR_SRE_MASK |
                PORT_PCR_PE_MASK |
                PORT_PCR_PS_MASK
               )) | (uint32_t)(
                PORT_PCR_MUX(0x01)
               ));
  /* PORTE_PCR26: ISF=0,MUX=1,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTE_PCR26 = (uint32_t)((PORTE_PCR26 & (uint32_t)~(uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_MUX(0x06) |
                 PORT_PCR_DSE_MASK |
                 PORT_PCR_ODE_MASK |
                 PORT_PCR_PFE_MASK |
                 PORT_PCR_SRE_MASK |
                 PORT_PCR_PE_MASK |
                 PORT_PCR_PS_MASK
                )) | (uint32_t)(
                 PORT_PCR_MUX(0x01)
                ));
  /* PORTE_PCR3: ISF=0,MUX=4,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTE_PCR3 = (uint32_t)((PORTE_PCR3 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_MUX(0x03) |
                PORT_PCR_DSE_MASK |
                PORT_PCR_ODE_MASK |
                PORT_PCR_PFE_MASK |
                PORT_PCR_SRE_MASK |
                PORT_PCR_PE_MASK |
                PORT_PCR_PS_MASK
               )) | (uint32_t)(
                PORT_PCR_MUX(0x04)
               ));
  /* PORTE_PCR1: ISF=0,MUX=4,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTE_PCR1 = (uint32_t)((PORTE_PCR1 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_MUX(0x03) |
                PORT_PCR_DSE_MASK |
                PORT_PCR_ODE_MASK |
                PORT_PCR_PFE_MASK |
                PORT_PCR_SRE_MASK |
                PORT_PCR_PE_MASK |
                PORT_PCR_PS_MASK
               )) | (uint32_t)(
                PORT_PCR_MUX(0x04)
               ));
  /* PORTE_PCR0: ISF=0,MUX=4,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTE_PCR0 = (uint32_t)((PORTE_PCR0 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_MUX(0x03) |
                PORT_PCR_DSE_MASK |
                PORT_PCR_ODE_MASK |
                PORT_PCR_PFE_MASK |
                PORT_PCR_SRE_MASK |
                PORT_PCR_PE_MASK |
                PORT_PCR_PS_MASK
               )) | (uint32_t)(
                PORT_PCR_MUX(0x04)
               ));
  /* PORTE_PCR5: ISF=0,MUX=4,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTE_PCR5 = (uint32_t)((PORTE_PCR5 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_MUX(0x03) |
                PORT_PCR_DSE_MASK |
                PORT_PCR_ODE_MASK |
                PORT_PCR_PFE_MASK |
                PORT_PCR_SRE_MASK |
                PORT_PCR_PE_MASK |
                PORT_PCR_PS_MASK
               )) | (uint32_t)(
                PORT_PCR_MUX(0x04)
               ));
  /* PORTE_PCR4: ISF=0,MUX=4,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTE_PCR4 = (uint32_t)((PORTE_PCR4 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_MUX(0x03) |
                PORT_PCR_DSE_MASK |
                PORT_PCR_ODE_MASK |
                PORT_PCR_PFE_MASK |
                PORT_PCR_SRE_MASK |
                PORT_PCR_PE_MASK |
                PORT_PCR_PS_MASK
               )) | (uint32_t)(
                PORT_PCR_MUX(0x04)
               ));
  /* PORTE_PCR2: ISF=0,MUX=4,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTE_PCR2 = (uint32_t)((PORTE_PCR2 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_MUX(0x03) |
                PORT_PCR_DSE_MASK |
                PORT_PCR_ODE_MASK |
                PORT_PCR_PFE_MASK |
                PORT_PCR_SRE_MASK |
                PORT_PCR_PE_MASK |
                PORT_PCR_PS_MASK
               )) | (uint32_t)(
                PORT_PCR_MUX(0x04)
               ));
  /* PORTD_PCR0: ISF=0,MUX=2,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTD_PCR0 = (uint32_t)((PORTD_PCR0 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_MUX(0x05) |
                PORT_PCR_DSE_MASK |
                PORT_PCR_ODE_MASK |
                PORT_PCR_PFE_MASK |
                PORT_PCR_SRE_MASK |
                PORT_PCR_PE_MASK |
                PORT_PCR_PS_MASK
               )) | (uint32_t)(
                PORT_PCR_MUX(0x02)
               ));
  /* PORTD_PCR3: ISF=0,MUX=2,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTD_PCR3 = (uint32_t)((PORTD_PCR3 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_MUX(0x05) |
                PORT_PCR_DSE_MASK |
                PORT_PCR_ODE_MASK |
                PORT_PCR_PFE_MASK |
                PORT_PCR_SRE_MASK |
                PORT_PCR_PE_MASK |
                PORT_PCR_PS_MASK
               )) | (uint32_t)(
                PORT_PCR_MUX(0x02)
               ));
  /* PORTD_PCR1: ISF=0,MUX=2,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTD_PCR1 = (uint32_t)((PORTD_PCR1 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_MUX(0x05) |
                PORT_PCR_DSE_MASK |
                PORT_PCR_ODE_MASK |
                PORT_PCR_PFE_MASK |
                PORT_PCR_SRE_MASK |
                PORT_PCR_PE_MASK |
                PORT_PCR_PS_MASK
               )) | (uint32_t)(
                PORT_PCR_MUX(0x02)
               ));
  /* PORTD_PCR2: ISF=0,MUX=2,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTD_PCR2 = (uint32_t)((PORTD_PCR2 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_MUX(0x05) |
                PORT_PCR_DSE_MASK |
                PORT_PCR_ODE_MASK |
                PORT_PCR_PFE_MASK |
                PORT_PCR_SRE_MASK |
                PORT_PCR_PE_MASK |
                PORT_PCR_PS_MASK
               )) | (uint32_t)(
                PORT_PCR_MUX(0x02)
               ));
  /* PORTD_PCR4: ISF=0,MUX=7,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTD_PCR4 = (uint32_t)((PORTD_PCR4 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_DSE_MASK |
                PORT_PCR_ODE_MASK |
                PORT_PCR_PFE_MASK |
                PORT_PCR_SRE_MASK |
                PORT_PCR_PE_MASK |
                PORT_PCR_PS_MASK
               )) | (uint32_t)(
                PORT_PCR_MUX(0x07)
               ));
  /* PORTD_PCR7: ISF=0,MUX=7,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTD_PCR7 = (uint32_t)((PORTD_PCR7 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_DSE_MASK |
                PORT_PCR_ODE_MASK |
                PORT_PCR_PFE_MASK |
                PORT_PCR_SRE_MASK |
                PORT_PCR_PE_MASK |
                PORT_PCR_PS_MASK
               )) | (uint32_t)(
                PORT_PCR_MUX(0x07)
               ));
  /* PORTD_PCR5: ISF=0,MUX=7,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTD_PCR5 = (uint32_t)((PORTD_PCR5 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_DSE_MASK |
                PORT_PCR_ODE_MASK |
                PORT_PCR_PFE_MASK |
                PORT_PCR_SRE_MASK |
                PORT_PCR_PE_MASK |
                PORT_PCR_PS_MASK
               )) | (uint32_t)(
                PORT_PCR_MUX(0x07)
               ));
  /* PORTD_PCR6: ISF=0,MUX=7,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTD_PCR6 = (uint32_t)((PORTD_PCR6 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_DSE_MASK |
                PORT_PCR_ODE_MASK |
                PORT_PCR_PFE_MASK |
                PORT_PCR_SRE_MASK |
                PORT_PCR_PE_MASK |
                PORT_PCR_PS_MASK
               )) | (uint32_t)(
                PORT_PCR_MUX(0x07)
               ));
  /* PORTB_PCR16: ISF=0,MUX=3,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTB_PCR16 = (uint32_t)((PORTB_PCR16 & (uint32_t)~(uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_MUX(0x04) |
                 PORT_PCR_DSE_MASK |
                 PORT_PCR_ODE_MASK |
                 PORT_PCR_PFE_MASK |
                 PORT_PCR_SRE_MASK |
                 PORT_PCR_PE_MASK |
                 PORT_PCR_PS_MASK
                )) | (uint32_t)(
                 PORT_PCR_MUX(0x03)
                ));
  /* PORTB_PCR17: ISF=0,MUX=3,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTB_PCR17 = (uint32_t)((PORTB_PCR17 & (uint32_t)~(uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_MUX(0x04) |
                 PORT_PCR_DSE_MASK |
                 PORT_PCR_ODE_MASK |
                 PORT_PCR_PFE_MASK |
                 PORT_PCR_SRE_MASK |
                 PORT_PCR_PE_MASK |
                 PORT_PCR_PS_MASK
                )) | (uint32_t)(
                 PORT_PCR_MUX(0x03)
                ));
  /* PORTC_PCR14: ISF=0,MUX=3,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTC_PCR14 = (uint32_t)((PORTC_PCR14 & (uint32_t)~(uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_MUX(0x04) |
                 PORT_PCR_DSE_MASK |
                 PORT_PCR_ODE_MASK |
                 PORT_PCR_PFE_MASK |
                 PORT_PCR_SRE_MASK |
                 PORT_PCR_PE_MASK |
                 PORT_PCR_PS_MASK
                )) | (uint32_t)(
                 PORT_PCR_MUX(0x03)
                ));
  /* PORTC_PCR15: ISF=0,MUX=3,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTC_PCR15 = (uint32_t)((PORTC_PCR15 & (uint32_t)~(uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_MUX(0x04) |
                 PORT_PCR_DSE_MASK |
                 PORT_PCR_ODE_MASK |
                 PORT_PCR_PFE_MASK |
                 PORT_PCR_SRE_MASK |
                 PORT_PCR_PE_MASK |
                 PORT_PCR_PS_MASK
                )) | (uint32_t)(
                 PORT_PCR_MUX(0x03)
                ));
  /* PORTB_PCR2: ISF=0,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTB_PCR2 &= (uint32_t)~(uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_DSE_MASK |
                 PORT_PCR_ODE_MASK |
                 PORT_PCR_PFE_MASK |
                 PORT_PCR_SRE_MASK |
                 PORT_PCR_PE_MASK |
                 PORT_PCR_PS_MASK
                );
  /* PORTB_PCR3: ISF=0,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTB_PCR3 &= (uint32_t)~(uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_DSE_MASK |
                 PORT_PCR_ODE_MASK |
                 PORT_PCR_PFE_MASK |
                 PORT_PCR_SRE_MASK |
                 PORT_PCR_PE_MASK |
                 PORT_PCR_PS_MASK
                );
  /* PORTB_PCR9: ISF=0,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTB_PCR9 &= (uint32_t)~(uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_DSE_MASK |
                 PORT_PCR_ODE_MASK |
                 PORT_PCR_PFE_MASK |
                 PORT_PCR_SRE_MASK |
                 PORT_PCR_PE_MASK |
                 PORT_PCR_PS_MASK
                );
  /* PORTB_PCR10: ISF=0,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTB_PCR10 &= (uint32_t)~(uint32_t)(
                  PORT_PCR_ISF_MASK |
                  PORT_PCR_DSE_MASK |
                  PORT_PCR_ODE_MASK |
                  PORT_PCR_PFE_MASK |
                  PORT_PCR_SRE_MASK |
                  PORT_PCR_PE_MASK |
                  PORT_PCR_PS_MASK
                 );
  /* PORTB_PCR11: ISF=0,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTB_PCR11 &= (uint32_t)~(uint32_t)(
                  PORT_PCR_ISF_MASK |
                  PORT_PCR_DSE_MASK |
                  PORT_PCR_ODE_MASK |
                  PORT_PCR_PFE_MASK |
                  PORT_PCR_SRE_MASK |
                  PORT_PCR_PE_MASK |
                  PORT_PCR_PS_MASK
                 );
  /* PORTB_PCR23: ISF=0,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTB_PCR23 &= (uint32_t)~(uint32_t)(
                  PORT_PCR_ISF_MASK |
                  PORT_PCR_DSE_MASK |
                  PORT_PCR_ODE_MASK |
                  PORT_PCR_PFE_MASK |
                  PORT_PCR_SRE_MASK |
                  PORT_PCR_PE_MASK |
                  PORT_PCR_PS_MASK
                 );
  /* PORTC_PCR2: ISF=0,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTC_PCR2 &= (uint32_t)~(uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_DSE_MASK |
                 PORT_PCR_ODE_MASK |
                 PORT_PCR_PFE_MASK |
                 PORT_PCR_SRE_MASK |
                 PORT_PCR_PE_MASK |
                 PORT_PCR_PS_MASK
                );
  /* PORTC_PCR3: ISF=0,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTC_PCR3 &= (uint32_t)~(uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_DSE_MASK |
                 PORT_PCR_ODE_MASK |
                 PORT_PCR_PFE_MASK |
                 PORT_PCR_SRE_MASK |
                 PORT_PCR_PE_MASK |
                 PORT_PCR_PS_MASK
                );
  /* PORTC_PCR4: ISF=0,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
  PORTC_PCR4 &= (uint32_t)~(uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_DSE_MASK |
                 PORT_PCR_ODE_MASK |
                 PORT_PCR_PFE_MASK |
                 PORT_PCR_SRE_MASK |
                 PORT_PCR_PE_MASK |
                 PORT_PCR_PS_MASK
                );
}


/* END pin_mux. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.4 [05.10]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
